spring:
  application:
    name: beer-service
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    
server:
  port: 8084
  
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
