spring:
  application:
    name: discovery

---
#spring:
#  profiles: peer1
eureka:
  #instance:
  # See blog post for details, modify /etc/hosts
  #  hostname: eureka-peer1
  # Either this one or the spring boot name must be the same
  # (it works without setting it too, using the alias UNKNOWN)
  #  appname: eureka-cluster
  #  leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka
    register-with-eureka: false
    fetch-registry: false
    #registryFetchIntervalSeconds: 5
    #instanceInfoReplicationIntervalSeconds: 5
    #initialInstanceInfoReplicationIntervalSeconds: 5
server:
  port: 8761