spring:
  application:
    name: discovery
  redis:
    host: testing-redis-server
    port: 6379

server:
  port: 8761
    
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@eureka-peer1:8761/eureka
    register-with-eureka: false
    fetch-registry: false
    