spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
    security:
        sessions: always

zuul:
  routes:
    beer-service:
      path: /beer-service/**
      sensitive-headers: Set-Cookie,Authorization
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8761
hystrix:
  command:
    beer-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
