spring:
  application:
    name: rating-service
  redis:
    host: localhost
    port: 6379
    
server:
  port: 8084

management:
    security:
        sessions: never
  
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
